<?php

namespace Database\Seeders;

use App\Models\Castle;
use Illuminate\Database\Seeder;

class CastleSeeder extends Seeder
{
    public function run(): void
    {
        $castles = [
            [
                'name' => '五稜郭',
                'name_korean' => '고료카쿠',
                'prefecture' => '北海道',
                'latitude' => 41.7915,
                'longitude' => 140.7542,
                'description' => '일본 최초의 서양식 성곽으로 별 모양의 독특한 구조를 가지고 있다.',
                'historical_info' => '1857년 설계되어 1864년 완성된 서양식 성곽으로, 보신전쟁 마지막 사무라이 전투 현장이다.',
                'official_stamp_location' => '하코다테 부교소 이타쿠라 휴게소, 고료카쿠 타워 매표소',
                'visiting_hours' => '09:00-18:00',
                'entrance_fee' => 500,
                'address' => '44 Goryokaku-cho, Hakodate, Hokkaido',
                'access_method' => 'JR 하코다테역에서 버스로 고료카쿠공원입구까지, 도보 10분',
                'official_website' => 'https://www.goryokaku-tower.co.jp/en/'
            ],
            [
                'name' => '弘前城',
                'name_korean' => '히로사키성',
                'prefecture' => '青森県',
                'latitude' => 40.6079291,
                'longitude' => 140.46366052462452,
                'description' => '벚꽃으로 유명한 아름다운 성으로 현재 복원 공사가 진행 중이다.',
                'historical_info' => '1603년 츠가루 타메노부가 축성을 시작하여 1610년 완성되었다.',
                'official_stamp_location' => '히로사키성 안내센터',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 320,
                'address' => '1 Shimo-Shirogane-cho, Hirosaki, Aomori',
                'access_method' => 'JR 히로사키역에서 버스로 시야쿠쇼마에까지, 도보 5분',
                'official_website' => 'https://www.hirosakipark.jp/en/'
            ],
            [
                'name' => '会津若松城',
                'name_korean' => '아이즈와카마츠성',
                'prefecture' => '福島県',
                'latitude' => 37.48773525,
                'longitude' => 139.92976605913537,
                'description' => '백호대의 역사로 유명한 성으로 츠루가성이라고도 불린다.',
                'historical_info' => '1384년 아시나 나오모리에 의해 축성되기 시작하여 1965년 재건되었다.',
                'official_stamp_location' => '천수각 내부 매장',
                'visiting_hours' => '08:30-17:00',
                'entrance_fee' => 410,
                'address' => '1-1 Oote-machi, Aizu Wakamatsu-shi, Fukushima',
                'access_method' => 'JR 아이즈와카마츠역에서 버스로 츠루가조키타구치까지, 도보 3분',
                'official_website' => 'http://www.tsurugajo.com/language/eng/'
            ],
            [
                'name' => '江戸城',
                'name_korean' => '에도성',
                'prefecture' => '東京都',
                'latitude' => 35.6823383,
                'longitude' => 139.75217857343807,
                'description' => '일본의 수도 도쿄에 위치한 대표적인 성으로, 현재 황궁이 자리하고 있다.',
                'historical_info' => '1457년 오타 도칸에 의해 축성된 성으로, 에도 막부의 중심지였다.',
                'official_stamp_location' => '난코, 와다쿠라, 키타노마루 휴게소',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 0,
                'address' => 'Chiyoda, Chiyoda-ku, Tokyo',
                'access_method' => 'JR 도쿄역 또는 오테마치 지하철역에서 도보 5분',
                'official_website' => 'https://visit-chiyoda.tokyo.t.ie.hp.transer.com/app/en/spot/detail/405'
            ],
            [
                'name' => '小田原城',
                'name_korean' => '오다와라성',
                'prefecture' => '神奈川県',
                'latitude' => 35.25105465,
                'longitude' => 139.15342492702024,
                'description' => '호조 가문이 5대에 걸쳐 관동을 지배한 난공불락의 성이다.',
                'historical_info' => '1417년 오모리 요리하루에 의해 축성되어 호조 가문이 발전시켰다.',
                'official_stamp_location' => '천수각 1층',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 510,
                'address' => 'Jonai, Odawara, Kanagawa',
                'access_method' => 'JR 오다와라역에서 도보 10분',
                'official_website' => 'http://www.odawara-kankou.com.e.jk.hp.transer.com/spot/spot_area/jyoushi.html'
            ],
            [
                'name' => '上田城',
                'name_korean' => '우에다성',
                'prefecture' => '長野県',
                'latitude' => 36.404044,
                'longitude' => 138.24374673215738,
                'description' => '사나다 마사유키가 축성한 성으로 도쿠가와군을 두 번 물리친 명성을 가지고 있다.',
                'historical_info' => '1583년 사나다 마사유키에 의해 축성되었다.',
                'official_stamp_location' => '우에다시 박물관, 우에다시 관광안내소',
                'visiting_hours' => '08:30-17:00',
                'entrance_fee' => 300,
                'address' => '4-6 Ninomaru, Ueda, Nagano',
                'access_method' => 'JR 우에다역에서 도보 10분',
                'official_website' => 'https://go.ueda-kanko.or.jp/special/castle_town/'
            ],
            [
                'name' => '松本城',
                'name_korean' => '마츠모토성',
                'prefecture' => '長野県',
                'latitude' => 36.23863525,
                'longitude' => 137.9688708786901,
                'description' => '일본에서 가장 오래된 목조 천수각이 있는 성이다.',
                'historical_info' => '1504년 시마다타 시게요리에 의해 축성되기 시작했다.',
                'official_stamp_location' => '마츠모토성 관리사무소',
                'visiting_hours' => '08:30-17:00',
                'entrance_fee' => 700,
                'address' => '4-1 Marunouchi, Matsumoto, Nagano',
                'access_method' => 'JR 마츠모토역에서 도보 15분',
                'official_website' => 'https://www.matsumoto-castle.jp/lang/'
            ],
            [
                'name' => '金沢城',
                'name_korean' => '가나자와성',
                'prefecture' => '石川県',
                'latitude' => 36.565600450000005,
                'longitude' => 136.6595753027176,
                'description' => '마에다 가문의 본거지로 겐로쿠엔과 함께 아름다운 경관을 이룬다.',
                'historical_info' => '1583년 마에다 토시이에가 입성하여 발전시킨 성이다.',
                'official_stamp_location' => '니노마루 안내센터, 이시카와몬 입구 안내센터',
                'visiting_hours' => '07:00-18:00',
                'entrance_fee' => 320,
                'address' => '1-1 Marunouchi, Kanazawa, Ishikawa',
                'access_method' => 'JR 가나자와역에서 버스로 겐로쿠엔시타까지, 도보 5분',
                'official_website' => 'http://www.pref.ishikawa.jp/siro-niwa/english/top.html'
            ],
            [
                'name' => '丸岡城',
                'name_korean' => '마루오카성',
                'prefecture' => '福井県',
                'latitude' => 36.15235865,
                'longitude' => 136.27212515000002,
                'description' => '일본에서 가장 오래된 목조 천수각 중 하나이다.',
                'historical_info' => '1576년 시바타 카츠이에의 조카 카츠토요에 의해 축성되었다.',
                'official_stamp_location' => '카스미가성 공원 관리사무소 (매표소)',
                'visiting_hours' => '08:30-17:00',
                'entrance_fee' => 450,
                'address' => '1-59 Maruoka-cho Kasumi-cho, Sakai, Fukui',
                'access_method' => 'JR 후쿠이역에서 버스로 마루오카조까지, 도보 5분',
                'official_website' => 'https://enjoy.pref.fukui.lg.jp/en/spot/spot-20/'
            ],
            [
                'name' => '犬山城',
                'name_korean' => '이누야마성',
                'prefecture' => '愛知県',
                'latitude' => 35.3883304,
                'longitude' => 136.9392776,
                'description' => '기소강변에 위치한 아름다운 경치의 성이다.',
                'historical_info' => '1537년 오다 노부야스에 의해 축성되었다.',
                'official_stamp_location' => '성문 2층, 이누야마성 관리사무소',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 550,
                'address' => '65-2 Inuyama-Kitakoken, Inuyama, Aichi',
                'access_method' => '메이테츠 이누야마유엔역에서 도보 15분',
                'official_website' => 'https://inuyamajo.jp/'
            ],
            [
                'name' => '名古屋城',
                'name_korean' => '나고야성',
                'prefecture' => '愛知県',
                'latitude' => 35.1853191,
                'longitude' => 136.899177,
                'description' => '도쿠가와 이에야스가 축성한 성으로, 금빛 샤치호코로 유명하다.',
                'historical_info' => '1612년 도쿠가와 이에야스의 명령으로 축성되었다.',
                'official_stamp_location' => '정문 및 동문 개찰구, 종합안내소',
                'visiting_hours' => '09:00-16:30',
                'entrance_fee' => 500,
                'address' => '1-1, Honmaru, Naka-ku, Nagoya, Aichi',
                'access_method' => '시야쿠쇼 지하철역에서 도보 5분',
                'official_website' => 'https://www.nagoyajo.city.nagoya.jp/en/'
            ],
            [
                'name' => '彦根城',
                'name_korean' => '히코네성',
                'prefecture' => '滋賀県',
                'latitude' => 35.2771013,
                'longitude' => 136.25172038647025,
                'description' => '비와호가 보이는 아름다운 성으로 히코냥으로도 유명하다.',
                'historical_info' => '1622년 이이 나오마사의 아들 나오카츠에 의해 완성되었다.',
                'official_stamp_location' => '히코네성 관리사무소 (히코네시 개국기념관)',
                'visiting_hours' => '08:30-17:00',
                'entrance_fee' => 800,
                'address' => '1-1, Konki-cho, Hikone, Shiga',
                'access_method' => 'JR 히코네역에서 도보 15분',
                'official_website' => 'https://visit.hikoneshi.com/en/castle/admission/'
            ],
            [
                'name' => '二条城',
                'name_korean' => '니조성',
                'prefecture' => '京都府',
                'latitude' => 35.01417,
                'longitude' => 135.7475,
                'description' => '에도 막부의 교토 거점이었던 성이다.',
                'historical_info' => '1603년 도쿠가와 이에야스에 의해 축성되었다.',
                'official_stamp_location' => '휴게소',
                'visiting_hours' => '08:45-17:00',
                'entrance_fee' => 1300,
                'address' => '541 Nijojo-cho, Nakakyo-ku, Kyoto, Kyoto',
                'access_method' => 'JR 교토역에서 버스로 니조조마에까지, 또는 니조조마에 지하철역',
                'official_website' => 'http://nijo-jocastle.city.kyoto.lg.jp/?lang=en'
            ],
            [
                'name' => '大阪城',
                'name_korean' => '오사카성',
                'prefecture' => '大阪府',
                'latitude' => 34.6857,
                'longitude' => 135.5222,
                'description' => '도요토미 히데요시가 축성한 일본의 대표적인 성이다.',
                'historical_info' => '1583년 도요토미 히데요시에 의해 축성되었으며, 안토-모모야마 시대의 상징이다.',
                'official_stamp_location' => '천수각 1층 안내소',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 600,
                'address' => '1-1 Osakajo, Chuo-ku, Osaka, Osaka',
                'access_method' => 'JR 오사카조코엔역 또는 모리노미야역에서 도보 15분',
                'official_website' => 'https://www.osakacastle.net/english/'
            ],
            [
                'name' => '姫路城',
                'name_korean' => '히메지성',
                'prefecture' => '兵庫県',
                'latitude' => 34.839331349,
                'longitude' => 134.69402,
                'description' => '세계문화유산으로 지정된 일본의 대표적인 목조 성이다.',
                'historical_info' => '1333년 아카마츠 노리무라가 축성하기 시작하여 여러 차례 개축되었다.',
                'official_stamp_location' => '정문 옆 관리사무소',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 1000,
                'address' => '68 Hon-cho, Himeji, Hyogo',
                'access_method' => 'JR 히메지역에서 도보 20분',
                'official_website' => 'http://www.himejicastle.jp/en/'
            ],
            [
                'name' => '松江城',
                'name_korean' => '마츠에성',
                'prefecture' => '島根県',
                'latitude' => 35.474514,
                'longitude' => 133.050833,
                'description' => '신지코 호수 근처에 위치한 흑색의 아름다운 성이다.',
                'historical_info' => '1611년 호리오 요시하루에 의해 완성되었다.',
                'official_stamp_location' => '천수각 접수처',
                'visiting_hours' => '08:30-18:30',
                'entrance_fee' => 680,
                'address' => '1-5 Tono-machi, Matsue, Shimane',
                'access_method' => 'JR 마츠에역에서 버스로 오테마에까지, 도보 5분',
                'official_website' => 'https://www.visit-matsue.com/discover/city_centre/north_side'
            ],
            [
                'name' => '備中松山城',
                'name_korean' => '비추마츠야마성',
                'prefecture' => '岡山県',
                'latitude' => 34.80870575,
                'longitude' => 133.62214678,
                'description' => '일본에서 가장 높은 곳에 위치한 현존 천수각을 가진 성이다.',
                'historical_info' => '1240년 아키바 시게토시에 의해 축성되기 시작했다.',
                'official_stamp_location' => '매표소',
                'visiting_hours' => '09:00-17:30',
                'entrance_fee' => 500,
                'address' => '1 Uchi-Yamashita, Takahashi, Okayama',
                'access_method' => 'JR 비추타카하시역에서 버스로 마츠야마성 등산로까지, 도보 50분',
                'official_website' => 'https://www.city.takahashi.okayama.jp/'
            ],
            [
                'name' => '広島城',
                'name_korean' => '히로시마성',
                'prefecture' => '広島県',
                'latitude' => 34.402500,
                'longitude' => 132.459444,
                'description' => '모리 테루모토가 축성한 성으로 원폭 투하로 소실되었다가 복원되었다.',
                'historical_info' => '1589년 모리 테루모토에 의해 축성되었다.',
                'official_stamp_location' => '1층 박물관 매장',
                'visiting_hours' => '09:00-18:00',
                'entrance_fee' => 370,
                'address' => '21-1 Moto-machi, Naka-ku, Hiroshima, Hiroshima',
                'access_method' => 'JR 히로시마역에서 전차로 가미야초히가시까지, 도보 15분',
                'official_website' => 'https://visithiroshima.net/things_to_do/attractions/historical_places/hiroshima_castle.html'
            ],
            [
                'name' => '丸亀城',
                'name_korean' => '마루가메성',
                'prefecture' => '香川県',
                'latitude' => 34.2860216,
                'longitude' => 133.8001009,
                'description' => '일본에서 가장 높은 석벽을 자랑하는 성이다.',
                'historical_info' => '1597년 이코마 치카마사에 의해 축성되었다.',
                'official_stamp_location' => '천수각 내부',
                'visiting_hours' => '09:00-16:30',
                'entrance_fee' => 200,
                'address' => 'Ichiban-cho, Marugame, Kagawa',
                'access_method' => 'JR 마루가메역에서 도보 10분',
                'official_website' => 'https://www-city-marugame-lg-jp.translate.goog/site/castle/'
            ],
            [
                'name' => '松山城',
                'name_korean' => '마츠야마성',
                'prefecture' => '愛媛県',
                'latitude' => 33.845556,
                'longitude' => 132.765833,
                'description' => '가츠야마산 정상에 위치한 현존 천수각이 있는 성이다.',
                'historical_info' => '1602년 가토 요시아키에 의해 축성되기 시작했다.',
                'official_stamp_location' => '천수각 입구',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 520,
                'address' => '1 Marunouchi, Matsuyama, Ehime',
                'access_method' => 'JR 마츠야마역에서 전차로 오카이도까지, 로프웨이 도보 5분',
                'official_website' => 'https://en.matsuyama-sightseeing.com/appeal/castle/'
            ],
            [
                'name' => '宇和島城',
                'name_korean' => '우와지마성',
                'prefecture' => '愛媛県',
                'latitude' => 33.2198186,
                'longitude' => 132.56473291,
                'description' => '바다를 바라보는 아름다운 현존 천수각이 있는 성이다.',
                'historical_info' => '1595년 도도 다카토라에 의해 축성되었다.',
                'official_stamp_location' => '천수각 내부',
                'visiting_hours' => '06:00-18:30',
                'entrance_fee' => 200,
                'address' => '3 Marunouchi, Uwajima, Ehime',
                'access_method' => 'JR 우와지마역에서 도보 20분',
                'official_website' => 'https://uwajima-tourism.org/en/spot/detail/place_id/72/'
            ],
            [
                'name' => '高知城',
                'name_korean' => '고치성',
                'prefecture' => '高知県',
                'latitude' => 33.560691,
                'longitude' => 133.53145881,
                'description' => '야마우치 가문의 성으로 혼마루 전체가 현존하는 유일한 성이다.',
                'historical_info' => '1603년 야마우치 카즈토요에 의해 축성되었다.',
                'official_stamp_location' => '천수각 입구',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 420,
                'address' => '1-2-1 Marunouchi, Kochi, Kochi',
                'access_method' => 'JR 고치역에서 전차로 하리마야바시 경유 고치조마에역까지, 도보 5분',
                'official_website' => 'https://visitkochijapan.com/en/see-and-do/10009'
            ],
            [
                'name' => '熊本城',
                'name_korean' => '구마모토성',
                'prefecture' => '熊本県',
                'latitude' => 32.8061,
                'longitude' => 130.7060,
                'description' => '가토 기요마사가 축성한 난공불락의 성으로 불린다.',
                'historical_info' => '1607년 가토 기요마사에 의해 완성되었다.',
                'official_stamp_location' => '니노마루 매표소, 와쿠와쿠자 매표소, 남입구 매표소, 북입구 매표소',
                'visiting_hours' => '09:00-17:00',
                'entrance_fee' => 800,
                'address' => '1-1 Honmaru, Chuo-ku, Kumamoto, Kumamoto',
                'access_method' => 'JR 구마모토역에서 전차로 구마모토조/시야쿠쇼마에역까지, 사쿠라노바바 조사이엔까지 도보 10분',
                'official_website' => 'https://castle.kumamoto-guide.jp/en/'
            ],
            [
                'name' => '首里城',
                'name_korean' => '슈리성',
                'prefecture' => '沖縄県',
                'latitude' => 26.217222,
                'longitude' => 127.719444,
                'description' => '류큐 왕국의 왕궁이었던 독특한 건축양식의 성이다.',
                'historical_info' => '14세기경 축성되어 류큐 왕국의 정치, 외교, 문화의 중심지였다.',
                'official_stamp_location' => '수이무이칸',
                'visiting_hours' => '09:00-18:00',
                'entrance_fee' => 400,
                'address' => '1-2 Shuri-Kinjo-cho, Naha, Okinawa',
                'access_method' => '모노레일로 슈리역 또는 기보역까지, 슈레이몬까지 도보 15분',
                'official_website' => 'http://oki-park.jp/shurijo/en/'
            ]
        ];

        foreach ($castles as $castle) {
            Castle::create($castle);
        }
    }
}