version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: castle24-app
    container_name: castle24-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - castle24

  webserver:
    image: nginx:alpine
    container_name: castle24-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/ssl:/etc/ssl/certs
      - ./docker/ssl:/etc/ssl/private
    networks:
      - castle24

networks:
  castle24:
    driver: bridge